### PR TITLE
.github/workflows/ansible-lint.yml: fix 'rich' dependency requirement

### PR DESCRIPTION
**Pull request by kpouget**
This PR fixes the test .github/workflows/ansible-lint.yml

Fix found in https://github.com/ansible/ansible-lint-action/issues/59

### CODE REVIEW

**Comment by osherdp** [comment]
@kpouget just FYI
if you'll cc someone on PR description, it will ping him only :smile:

**Comment by kpouget** [comment]
> @kpouget just FYI if you'll cc someone on PR description, it will ping him only smile

oh, I didn't know that, sorry for the spam :# :# :#

**Comment by sagidayan** [comment]
/ok-to-test

Thanks @kpouget !
Will not enable github actions just yet - but I do want this merged, for the day I enable them.

**Comment by kpouget** [comment]
I pushed minor updates to address the linter issues that were introduced while the Github Action check was down

**Comment by sagidayan** [comment]
@kpouget anything else you want to test?

**Comment by kpouget** [comment]
@sagidayan no, PR good from my POV

**Review by sagidayan — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
