### PR TITLE
Fix GPU operator bundle build helper not including all dev tools

### PR DESCRIPTION
**Pull request by mresvanis**
This PR adds `git`, `make`, `jq` and `yq` in the GPU operator bundle builder helper container, as they are required by the bash scripts that build the operator image from its `master` branch and the respective operator bundle.

Signed-off-by: Michail Resvanis <mresvani@redhat.com>

### CODE REVIEW

**Comment by kpouget** [comment]
I was wondering why these packages were missing ... but they were removed with the last [update](https://github.com/rh-ecosystem-edge/ci-artifacts/commit/67534bc2e28b93730c2877a1044662ae35b5cd1f) of the Dockerfile 🙃

**Comment by mresvanis** [comment]
> I was wondering why these packages were missing ... but they were removed with the last [update](https://github.com/rh-ecosystem-edge/ci-artifacts/commit/67534bc2e28b93730c2877a1044662ae35b5cd1f) of the Dockerfile upside_down_face

Exactly, in [this](https://github.com/rh-ecosystem-edge/ci-artifacts/pull/44) PR the `buildah` [Containerfile](https://github.com/containers/buildah/blob/main/contrib/buildahimage/upstream/Containerfile) was updated to the latest one, which did not include the afore-mentioned dependencies, resulting in breaking the GPU operator image build scripts :)

**Pull request merged**
