### PR TITLE
cluster_deploy_operator: new generic role to deploy an operator 

### PR DESCRIPTION
**Pull request by kpouget**
This PR creates a new toolbox command, which allows deploying any operator from OperatorHub, by specifying its PackageManifest name and SourceCatalog name:
```
./run_toolbox.py cluster deploy_operator
```
eg:
```
 ./run_toolbox.py cluster deploy_operator certified-operators gpu-operator-certified openshift-operators --channel=v1.8 --version=1.8.2 --deploy-cr=true --ns-monitoring=true
```
I also rewrote the GPU Operator and NFD deployment entrypoints to transparently use these roles, instead of `gpu_operator_deploy_from_operatorhub` and `nfd_operator_deploy_from_operatorhub`.

I don't see any reason to keep these last two roles, but I didn't delete them yet...

### CODE REVIEW

**Comment by kpouget** [comment]
I'll have to remove this commit https://github.com/rh-ecosystem-edge/ci-artifacts/pull/7/commits/6059ef10634a63ca7a83a5a5b219ab162e25efdc, I don't understand why Github doesn't complain about it nor remove it, 
maybe because this repo has an identical-but-not-bit-to-bit identical commit https://github.com/rh-ecosystem-edge/ci-artifacts/commit/58983bc57ea4a705c95d0276ad10f13c8af36242 in the tree (wasn't cherry-picked 🙃 )

**Comment by sagidayan** [comment]
@kpouget Is it Okay if I close this PR? Since we have these commits in #9 ?

**Comment by kpouget** [comment]
as you prefer, yes

**Comment by kpouget** [comment]
merged in https://github.com/rh-ecosystem-edge/ci-artifacts/pull/9

/close

**Pull request closed without merging**
