### PR TITLE
Add mresvanis to OWNERS

### PR DESCRIPTION
**Pull request by mresvanis**
This changes adds `mresvanis` to the approvers and reviewers of this repository.

### CODE REVIEW

**Comment by sagidayan** [comment]
/uncc @osherdp 
/cc @fabiendupont 
/ok-to-test
/approve

This PR needs one of the org owners (@fabiendupont) to add you as a member.

**Comment by osherdp** [comment]
@mresvanis please ask @fabiendupont to send you an invite from https://github.com/orgs/rh-ecosystem-edge/people

**Pull request merged**
