### PR TITLE
gpu_operator fixes

### PR DESCRIPTION
**Pull request by kwozyman**
Use upstream container image repo and some minor fixes relating to gpu_operator

### CODE REVIEW

**Comment by kpouget** [comment]
as discussed offline, looks good to me

I think it would be worth adding a script in `testing/<something>` deploying the GPU Operator with the `--with-driver` flag, so that it can be easily tested,

eg: https://github.com/rh-ecosystem-edge/ci-artifacts/blob/master/testing/prow/gpu-operator.sh#L517

which works by adding this line in the top-most commit of the PR: 
```
test-path: prow gpu-operator publish_master_bundle 
```
then trigger it in the PR by requesting
```
/test test-commit
```

**Comment by kpouget** [comment]
> @kwozyman: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/test-commit 	[6c4a9fe](https://github.com/rh-ecosystem-edge/ci-artifacts/commit/6c4a9fede4f75d490971ca2391789d7e44426cad) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/rh-ecosystem-edge_ci-artifacts/27/pull-ci-rh-ecosystem-edge-ci-artifacts-master-test-commit/1504356198172856320) 	true 	`/test test-commit`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=rh-ecosystem-edge&repo=ci-artifacts&pr=27). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:kwozyman).

🤔 
is this test _required_? and `always_run: true`?
the failure was expected, 
```
 Nothing to test in 6c4a9fede4f75d490971ca2391789d7e44426cad. 
```
as there is no (not yet) `test-path` in the top-most commit

**Comment by kpouget** [comment]
flake ...

**Review by fabiendupont — APPROVED** [review]

**Pull request merged**
